image: rambabusaravanan/firebase

default:
  before_script:
    - npm i

stages:
  # - install
  - test
  - build
  # - deploy

build_job:
  state: build
  script: npm run build

# install_job:
#   stage: install
#   script:
#     - npm i

test_job:
  stage: test
  script: 
    - npm test


