image: node:10.15.3

stages:
  - install
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install_job:
  stage: install
  script:
    - npm i
  # only:
  #   changes:
  #     - package-lock.json
      

build_job:
  stage: build
  script:
    - npm run build
  cache:
    key: build-cache
    paths:
      - build/


unit_test:
  stage: test
  script:
    - npm test

code_quality:
  stage: test
  # script:
  #   - npm test
  # cache: 
  #   key: install-cache
  #   paths:
  #     - node_modules/

performance:
  stage: test
  # script:
  #   - npm test
  # cache: 
  #   key: install-cache
  #   paths:
  #     - node_modules/

deploy_job:
  image: rambabusaravanan/firebase
  stage: deploy
  only:
    - developer
  script:
    - firebase use oalmilktea --token 1//0gC-gxEefbI7ZCgYIARAAGBASNwF-L9Ir_Aio4tkbmnoq2RuhvbC5RlbILDU8clHhx4CuNUM5VOqeBNyo3fmTjp4Zo32W9C-T4Jk
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token 1//0gC-gxEefbI7ZCgYIARAAGBASNwF-L9Ir_Aio4tkbmnoq2RuhvbC5RlbILDU8clHhx4CuNUM5VOqeBNyo3fmTjp4Zo32W9C-T4Jk
  cache: 
    key: build-cache
    paths:
      - build/