image: rambabusaravanan/firebase

# default:
before_script:
  - npm i

stages:
  - build
  - test
  - deploy
  # - install


build_job:
  stage: build
  script: npm run build

# install_job:
#   stage: install
#   script:
#     - npm i

test_job:
  stage: test
  script: 
    - npm test


cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 

deploy_job:
  stage: deploy
  only:
    - developer
  script:
    - firebase use oalmilktea --token 1//0gC-gxEefbI7ZCgYIARAAGBASNwF-L9Ir_Aio4tkbmnoq2RuhvbC5RlbILDU8clHhx4CuNUM5VOqeBNyo3fmTjp4Zo32W9C-T4Jk
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token 1//0gC-gxEefbI7ZCgYIARAAGBASNwF-L9Ir_Aio4tkbmnoq2RuhvbC5RlbILDU8clHhx4CuNUM5VOqeBNyo3fmTjp4Zo32W9C-T4Jk