image: rambabusaravanan/firebase

before-script:
  - npm i

stages:
  - test
  # - build
  # - deploy

# build_job:
#   state: build
#   script: npm run build

test_job:
  state: test
  script: 
    - npm test


