image: rambabusaravanan/firebase

default:
  before_script:
    - npm i

stages:
  - test
  - build
  # - install
  # - deploy

build_job:
  stage: build
  script: npm run build

# install_job:
#   stage: install
#   script:
#     - npm i

test_job:
  stage: test
  script: 
    - npm test


